# Generated by Django 3.0.2 on 2020-02-20 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('postcode', models.CharField(max_length=10, verbose_name='Почтовый индекс')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('country_code', models.CharField(max_length=5, verbose_name='Код страны')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=10, verbose_name='Количество комнат')),
                ('floor', models.IntegerField(blank=True, default=1, null=True, verbose_name='Этаж')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('square', models.FloatField(verbose_name='Площадь')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Главное фото')),
                ('date_of_arrival', models.DateField(help_text='гггг-мм-дд', verbose_name='Дата прибытия')),
                ('date_of_departure', models.DateField(help_text='гггг-мм-дд', verbose_name='Дата отбытия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('status', models.BooleanField(verbose_name='Свободно ли?')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='home.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.Apartment')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Type', verbose_name='Тип недвижимости'),
        ),
    ]
