# Generated by Django 3.0.2 on 2020-02-13 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('postcode', models.CharField(max_length=10, verbose_name='Почтовый индекс')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('country_code', models.CharField(max_length=5, verbose_name='Код страны')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='yourthome.Address', verbose_name='Адрес'),
        ),
    ]
