# Generated by Django 3.0.2 on 2020-02-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Главное фото'),
        ),
    ]
