# Generated by Django 3.0.3 on 2020-04-09 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewApartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.PositiveSmallIntegerField(null=True, verbose_name='Количество комнат')),
                ('floor', models.PositiveSmallIntegerField(null=True, verbose_name='Этаж')),
                ('area', models.FloatField(null=True, verbose_name='Площадь')),
                ('location', models.CharField(max_length=269, verbose_name='Расположение')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Главное фото')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('another_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Конвертированная цена')),
                ('status', models.BooleanField(default=True, verbose_name='Статус объекта недвижимости')),
                ('furniture', models.BooleanField(default=False, verbose_name='Мебель')),
                ('heat', models.BooleanField(default=False, verbose_name='Отопление')),
                ('gas', models.BooleanField(default=False, verbose_name='Газ')),
                ('electricity', models.BooleanField(default=False, verbose_name='Электричество')),
                ('internet', models.BooleanField(default=False, verbose_name='Интернет')),
                ('phone', models.BooleanField(default=False, verbose_name='Телевонная линия')),
                ('parking', models.BooleanField(blank=True, default=False, null=True, verbose_name='Парковка')),
                ('elevator', models.BooleanField(blank=True, default=False, null=True, verbose_name='Лифт')),
                ('security', models.BooleanField(blank=True, default=False, null=True, verbose_name='Охрана')),
                ('construction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Construction', verbose_name='Тип сторения')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_new', to='home.Contact', verbose_name='Контактиные данные')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Currency', verbose_name='Валюта')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Series', verbose_name='Серия')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.State', verbose_name='Состояние')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Type', verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'Новая квартира',
                'verbose_name_plural': 'Новые квартиры',
            },
        ),
        migrations.CreateModel(
            name='NewApartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_image', to='home.NewApartment')),
            ],
        ),
    ]
