# Generated by Django 3.0.3 on 2020-04-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newapartment_newapartmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Бишкек', max_length=70, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(default='8 микрорайон', max_length=170, verbose_name='Район'),
        ),
    ]
