# Generated by Django 3.0.3 on 2020-05-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200501_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Рядом есть')),
            ],
            options={
                'verbose_name': 'Рядом есть',
                'verbose_name_plural': 'Рядом есть',
            },
        ),
        migrations.CreateModel(
            name='ObjectsInApartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='В доме есть')),
            ],
            options={
                'verbose_name': 'В доме есть',
                'verbose_name_plural': 'В доме есть',
            },
        ),
    ]
