# Generated by Django 3.0.2 on 2020-02-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0002_auto_20200213_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='yourthome.Address', verbose_name='Адрес'),
        ),
    ]
