# Generated by Django 3.0.2 on 2020-02-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0003_auto_20200213_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='date_of_arrival',
            field=models.DateField(help_text='гггг-мм-дд', verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='date_of_departure',
            field=models.DateField(help_text='гггг-мм-дд', verbose_name='Дата отбытия'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
