# Generated by Django 3.0.2 on 2020-02-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0004_auto_20200215_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адресы'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourthome.Address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
