# Generated by Django 3.0.3 on 2020-03-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200328_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='photos',
        ),
    ]
