# Generated by Django 3.0.3 on 2020-04-15 23:15

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_apartment_tags'),
    ]

    operations = [

    ]
