# Generated by Django 3.0.3 on 2020-04-17 21:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200416_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='nearby_objects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=list, size=None),
        ),
    ]
