# Generated by Django 3.0.3 on 2020-04-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_task_taskimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskimage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Apartment'),
        ),
    ]
