# Generated by Django 3.0.3 on 2020-04-17 21:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_apartment_nearby_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='objects_in_apartment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), default=list, size=None, verbose_name='В квартире есть'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='nearby_objects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), default=list, size=None, verbose_name='Рядом есть'),
        ),
    ]
