# Generated by Django 3.0.2 on 2020-02-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0007_auto_20200218_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ManyToManyField(blank=True, to='yourthome.Image', verbose_name='Фотографии'),
        ),
    ]
