# Generated by Django 3.0.2 on 2020-02-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0009_auto_20200218_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='yourthome.Apartment'),
        ),
    ]
