# Generated by Django 3.0.3 on 2020-04-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200422_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartmentImage',
        ),
    ]
