# Generated by Django 3.0.2 on 2020-02-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0011_auto_20200218_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='yourthome.Image', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
