# Generated by Django 3.0.2 on 2020-02-17 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0012_auto_20200218_0256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='apartment',
        ),
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='yourthome.Address'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ManyToManyField(to='yourthome.Image', verbose_name='Фотографии'),
        ),
    ]
