# Generated by Django 3.0.3 on 2020-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200423_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='electricity',
            field=models.BooleanField(blank=True, null=True, verbose_name='Электричество'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='furniture',
            field=models.BooleanField(blank=True, null=True, verbose_name='Мебель'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='gas',
            field=models.BooleanField(blank=True, null=True, verbose_name='Газ'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='heat',
            field=models.BooleanField(blank=True, null=True, verbose_name='Отопление'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='internet',
            field=models.BooleanField(blank=True, null=True, verbose_name='Интернет'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='phone',
            field=models.BooleanField(blank=True, null=True, verbose_name='Телевонная линия'),
        ),
    ]
