# Generated by Django 3.0.2 on 2020-02-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0013_auto_20200218_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='yourthome.Address'),
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='image',
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yourthome.Image', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='photos/'),
        ),
    ]
