# Generated by Django 3.0.3 on 2020-04-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200423_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='tags',
        ),
    ]
