# Generated by Django 3.0.2 on 2020-02-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0014_auto_20200218_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yourthome.Apartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='yourthome.Address'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.png', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
