# Generated by Django 3.0.2 on 2020-02-18 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourthome', '0015_auto_20200218_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='yourthome.Apartment'),
        ),
    ]
